web:
    image: tutum/apache-php
    ports:
        - "80:80"
    volumes:
        - /var/www:/var/www
        - /var/www/docker/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
        - /var/www/docker/sites:/etc/apache2/sites-enabled
        - /var/www/docker/sites:/etc/apache2/sites-available
    environment:
     - ALLOW_OVERRIDE=true